### ISSUE TITLE
Version 3.5 with Java 7.80

### ISSUE THREAD

**Issue by Sphyncter** [angryziber/ipscan#88]
I see in the changelog that in the latest version of 3.5 that you have dropped support for Java 6.
I am running Java 7.80 but get the following error when launching. Is this intentional to have dropped support for Java 7 also? See attached screenshot.

![capture](https://cloud.githubusercontent.com/assets/25289130/22188676/64ebbe74-e167-11e6-8933-87679353f17b.JPG)

**Comment by smoke007** [comment]
I too am getting this error message after updating to version 3.5.  I am running Java 7 Update 75 on my workstation and can't upgrade past this Java version due to other incompatibilities with other software and newer java versions.  Can this be fixed or do I need to downgrade to an older version of Angry IP Scanner?  Thank you.

**Comment by angryziber** [comment]
Sorry about that, I didn't realize that SWT (the UI toolkit) has already switched to Java 8.
I have downgraded it to 4.6, so Java 7 can still be supported for some time.
